- type: job
  id: SyndAnarchykeeper # Оперативник
  name: job-name-anarchykeeper
  description: job-description-anarchy
  playTimeTracker: JobAnarchykeeperTracker
  requirements:
  startingGear: AnarchykeeperGear
  icon: "JobIconSyndieMarksman"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  extendedAccess:
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperCargoTechnician # Логист
  name: job-name-anarchykeeper-cargotechnician
  description: job-description-anarchykeeper-cargotechnician
  playTimeTracker: JobAnarchykeeperCargoTechnicianTracker
  requirements:
  startingGear: SyndieCargotechGear
  icon: "JobIconSyndieScientist"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  - Engineering
  - Cargo
  - NuclearOperative
  special:
  - !type:AddImplantSpecial
    implants: [ UplinkImplant ]

- type: job
  id: SyndAnarchykeeperSpecMarksman # Специалист - марксман
  name: Specialist Marksman
  description: job-description-anarchy
  playTimeTracker: JobSpecMarksmanTracker
  requirements:
  startingGear: AnarchykeeperGear
  icon: "JobIconSyndieMarksman"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  extendedAccess:
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperSpecMachinegunner # Специалист - пулеметчик
  name: Specialist Machinegunner
  description: job-description-anarchy
  playTimeTracker: JobSpecMachinegunnerTracker
  requirements:
  startingGear: AnarchykeeperGear
  icon: "JobIconSyndieMarksman"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  extendedAccess:
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperSpecMedic # Специалист - санитар
  name: Specialist Corpsman
  description: job-description-anarchy
  playTimeTracker: JobSpecMedicTracker
  requirements:
  startingGear: AnarchykeeperGear
  icon: "JobIconSyndieMarksman"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  extendedAccess:
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperOfficer # Офицер
  name: job-name-anarchykeeper-officer
  description: job-description-anarchykeeper-officer
  playTimeTracker: JobAnarchykeeperOfficerTracker
  requirements:
  - !type:SpeciesRequirement # Only humans
    species:
    - Human
  startingGear: AnarchykeeperOfficerGear
  icon: "JobIconMasterAtArms"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - NuclearOperative
  - Cargo
  - Engineering
  - Medical
