- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - Bagel VXS
  # - Box
  # - Cog
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Oasis
  # - Omega
  # - Packed
  # - Reach
  #- Train
  - Barnaul
  - Omsk

